// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	PostID   string     `json:"postID"`
	ParentID *string    `json:"parentID,omitempty"`
	AuthorID string     `json:"authorID"`
	Content  string     `json:"content"`
	Replies  []*Comment `json:"replies"`
}

type CommentConnection struct {
	Nodes    []*Comment `json:"nodes"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
	Content  string  `json:"content"`
}

type CreatePostInput struct {
	Title           string `json:"title"`
	Content         string `json:"content"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Post struct {
	ID              string             `json:"id"`
	AuthorID        string             `json:"authorID"`
	Title           string             `json:"title"`
	Content         string             `json:"content"`
	CommentsEnabled bool               `json:"commentsEnabled"`
	Comments        *CommentConnection `json:"comments"`
}

type Query struct {
}
