// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/graphql/resolver.go
//
// Generated by this command:
//
//	mockgen -source=internal/transport/graphql/resolver.go -destination=internal/transport/graphql/mock/mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/Henzer3/test-ozon/post-service/internal/entity"
	port "github.com/Henzer3/test-ozon/post-service/internal/port"
	gomock "go.uber.org/mock/gomock"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
	isgomock struct{}
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostService) CreatePost(ctx context.Context, input port.CreatePostInput) (entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, input)
	ret0, _ := ret[0].(entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceMockRecorder) CreatePost(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostService)(nil).CreatePost), ctx, input)
}

// Post mocks base method.
func (m *MockPostService) Post(ctx context.Context, id int64) (entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, id)
	ret0, _ := ret[0].(entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockPostServiceMockRecorder) Post(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockPostService)(nil).Post), ctx, id)
}

// Posts mocks base method.
func (m *MockPostService) Posts(ctx context.Context) ([]entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Posts", ctx)
	ret0, _ := ret[0].([]entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Posts indicates an expected call of Posts.
func (mr *MockPostServiceMockRecorder) Posts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Posts", reflect.TypeOf((*MockPostService)(nil).Posts), ctx)
}

// MockCommentService is a mock of CommentService interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
	isgomock struct{}
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// Comments mocks base method.
func (m *MockCommentService) Comments(ctx context.Context, input port.CommentPageInput) (entity.CommentPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comments", ctx, input)
	ret0, _ := ret[0].(entity.CommentPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Comments indicates an expected call of Comments.
func (mr *MockCommentServiceMockRecorder) Comments(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comments", reflect.TypeOf((*MockCommentService)(nil).Comments), ctx, input)
}

// CreateComment mocks base method.
func (m *MockCommentService) CreateComment(ctx context.Context, input port.CreateCommentInput) (entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, input)
	ret0, _ := ret[0].(entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentServiceMockRecorder) CreateComment(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentService)(nil).CreateComment), ctx, input)
}

// MockSubscriptionService is a mock of SubscriptionService interface.
type MockSubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceMockRecorder
	isgomock struct{}
}

// MockSubscriptionServiceMockRecorder is the mock recorder for MockSubscriptionService.
type MockSubscriptionServiceMockRecorder struct {
	mock *MockSubscriptionService
}

// NewMockSubscriptionService creates a new mock instance.
func NewMockSubscriptionService(ctrl *gomock.Controller) *MockSubscriptionService {
	mock := &MockSubscriptionService{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionService) EXPECT() *MockSubscriptionServiceMockRecorder {
	return m.recorder
}

// SubscribeComments mocks base method.
func (m *MockSubscriptionService) SubscribeComments(ctx context.Context, postID int64) (<-chan entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeComments", ctx, postID)
	ret0, _ := ret[0].(<-chan entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeComments indicates an expected call of SubscribeComments.
func (mr *MockSubscriptionServiceMockRecorder) SubscribeComments(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeComments", reflect.TypeOf((*MockSubscriptionService)(nil).SubscribeComments), ctx, postID)
}
