// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/post/post.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/post/post.go -destination=internal/usecase/post/mock/mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/Henzer3/test-ozon/post-service/internal/entity"
	port "github.com/Henzer3/test-ozon/post-service/internal/port"
	gomock "go.uber.org/mock/gomock"
)

// MockpostRepository is a mock of postRepository interface.
type MockpostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpostRepositoryMockRecorder
	isgomock struct{}
}

// MockpostRepositoryMockRecorder is the mock recorder for MockpostRepository.
type MockpostRepositoryMockRecorder struct {
	mock *MockpostRepository
}

// NewMockpostRepository creates a new mock instance.
func NewMockpostRepository(ctrl *gomock.Controller) *MockpostRepository {
	mock := &MockpostRepository{ctrl: ctrl}
	mock.recorder = &MockpostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostRepository) EXPECT() *MockpostRepositoryMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockpostRepository) CreatePost(ctx context.Context, input port.CreatePostInput) (entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, input)
	ret0, _ := ret[0].(entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockpostRepositoryMockRecorder) CreatePost(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockpostRepository)(nil).CreatePost), ctx, input)
}

// GetPost mocks base method.
func (m *MockpostRepository) GetPost(ctx context.Context, id int64) (entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, id)
	ret0, _ := ret[0].(entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockpostRepositoryMockRecorder) GetPost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockpostRepository)(nil).GetPost), ctx, id)
}

// GetPosts mocks base method.
func (m *MockpostRepository) GetPosts(ctx context.Context) ([]entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx)
	ret0, _ := ret[0].([]entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockpostRepositoryMockRecorder) GetPosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockpostRepository)(nil).GetPosts), ctx)
}

// MockcommentRepository is a mock of commentRepository interface.
type MockcommentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcommentRepositoryMockRecorder
	isgomock struct{}
}

// MockcommentRepositoryMockRecorder is the mock recorder for MockcommentRepository.
type MockcommentRepositoryMockRecorder struct {
	mock *MockcommentRepository
}

// NewMockcommentRepository creates a new mock instance.
func NewMockcommentRepository(ctrl *gomock.Controller) *MockcommentRepository {
	mock := &MockcommentRepository{ctrl: ctrl}
	mock.recorder = &MockcommentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommentRepository) EXPECT() *MockcommentRepositoryMockRecorder {
	return m.recorder
}

// Comments mocks base method.
func (m *MockcommentRepository) Comments(ctx context.Context, input port.CommentPageInput) (entity.CommentPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comments", ctx, input)
	ret0, _ := ret[0].(entity.CommentPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Comments indicates an expected call of Comments.
func (mr *MockcommentRepositoryMockRecorder) Comments(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comments", reflect.TypeOf((*MockcommentRepository)(nil).Comments), ctx, input)
}

// CreateComment mocks base method.
func (m *MockcommentRepository) CreateComment(ctx context.Context, input port.CreateCommentInput) (entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, input)
	ret0, _ := ret[0].(entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockcommentRepositoryMockRecorder) CreateComment(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockcommentRepository)(nil).CreateComment), ctx, input)
}

// GetComment mocks base method.
func (m *MockcommentRepository) GetComment(ctx context.Context, id int64) (entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ctx, id)
	ret0, _ := ret[0].(entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockcommentRepositoryMockRecorder) GetComment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockcommentRepository)(nil).GetComment), ctx, id)
}

// MockcommentBroker is a mock of commentBroker interface.
type MockcommentBroker struct {
	ctrl     *gomock.Controller
	recorder *MockcommentBrokerMockRecorder
	isgomock struct{}
}

// MockcommentBrokerMockRecorder is the mock recorder for MockcommentBroker.
type MockcommentBrokerMockRecorder struct {
	mock *MockcommentBroker
}

// NewMockcommentBroker creates a new mock instance.
func NewMockcommentBroker(ctrl *gomock.Controller) *MockcommentBroker {
	mock := &MockcommentBroker{ctrl: ctrl}
	mock.recorder = &MockcommentBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommentBroker) EXPECT() *MockcommentBrokerMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockcommentBroker) Publish(comment entity.Comment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", comment)
}

// Publish indicates an expected call of Publish.
func (mr *MockcommentBrokerMockRecorder) Publish(comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockcommentBroker)(nil).Publish), comment)
}

// Subscribe mocks base method.
func (m *MockcommentBroker) Subscribe(ctx context.Context, postID int64) <-chan entity.Comment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, postID)
	ret0, _ := ret[0].(<-chan entity.Comment)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockcommentBrokerMockRecorder) Subscribe(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockcommentBroker)(nil).Subscribe), ctx, postID)
}
