// Code generated by MockGen. DO NOT EDIT.
// Source: ../../entity/ports.go
//
// Generated by this command:
//
//	mockgen -source=../../entity/ports.go -destination=mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/Henzer3/test-ozon/sso-service/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuther is a mock of Auther interface.
type MockAuther struct {
	ctrl     *gomock.Controller
	recorder *MockAutherMockRecorder
	isgomock struct{}
}

// MockAutherMockRecorder is the mock recorder for MockAuther.
type MockAutherMockRecorder struct {
	mock *MockAuther
}

// NewMockAuther creates a new mock instance.
func NewMockAuther(ctrl *gomock.Controller) *MockAuther {
	mock := &MockAuther{ctrl: ctrl}
	mock.recorder = &MockAutherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuther) EXPECT() *MockAutherMockRecorder {
	return m.recorder
}

// IsAdmin mocks base method.
func (m *MockAuther) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockAutherMockRecorder) IsAdmin(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockAuther)(nil).IsAdmin), ctx, userID)
}

// Login mocks base method.
func (m *MockAuther) Login(ctx context.Context, email, password string, appID int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password, appID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAutherMockRecorder) Login(ctx, email, password, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuther)(nil).Login), ctx, email, password, appID)
}

// RegisterNewUser mocks base method.
func (m *MockAuther) RegisterNewUser(ctx context.Context, email, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNewUser", ctx, email, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterNewUser indicates an expected call of RegisterNewUser.
func (mr *MockAutherMockRecorder) RegisterNewUser(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewUser", reflect.TypeOf((*MockAuther)(nil).RegisterNewUser), ctx, email, password)
}

// Verify mocks base method.
func (m *MockAuther) Verify(ctx context.Context, token string) (entity.UserPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, token)
	ret0, _ := ret[0].(entity.UserPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockAutherMockRecorder) Verify(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockAuther)(nil).Verify), ctx, token)
}

// MockUserSaver is a mock of UserSaver interface.
type MockUserSaver struct {
	ctrl     *gomock.Controller
	recorder *MockUserSaverMockRecorder
	isgomock struct{}
}

// MockUserSaverMockRecorder is the mock recorder for MockUserSaver.
type MockUserSaverMockRecorder struct {
	mock *MockUserSaver
}

// NewMockUserSaver creates a new mock instance.
func NewMockUserSaver(ctrl *gomock.Controller) *MockUserSaver {
	mock := &MockUserSaver{ctrl: ctrl}
	mock.recorder = &MockUserSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSaver) EXPECT() *MockUserSaverMockRecorder {
	return m.recorder
}

// SaveUser mocks base method.
func (m *MockUserSaver) SaveUser(ctx context.Context, email string, passHash []byte, isAdmin bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, email, passHash, isAdmin)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserSaverMockRecorder) SaveUser(ctx, email, passHash, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserSaver)(nil).SaveUser), ctx, email, passHash, isAdmin)
}

// MockUserProvider is a mock of UserProvider interface.
type MockUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderMockRecorder
	isgomock struct{}
}

// MockUserProviderMockRecorder is the mock recorder for MockUserProvider.
type MockUserProviderMockRecorder struct {
	mock *MockUserProvider
}

// NewMockUserProvider creates a new mock instance.
func NewMockUserProvider(ctrl *gomock.Controller) *MockUserProvider {
	mock := &MockUserProvider{ctrl: ctrl}
	mock.recorder = &MockUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvider) EXPECT() *MockUserProviderMockRecorder {
	return m.recorder
}

// IsAdmin mocks base method.
func (m *MockUserProvider) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockUserProviderMockRecorder) IsAdmin(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockUserProvider)(nil).IsAdmin), ctx, userID)
}

// IsAdminExist mocks base method.
func (m *MockUserProvider) IsAdminExist(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdminExist", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdminExist indicates an expected call of IsAdminExist.
func (mr *MockUserProviderMockRecorder) IsAdminExist(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdminExist", reflect.TypeOf((*MockUserProvider)(nil).IsAdminExist), ctx)
}

// User mocks base method.
func (m *MockUserProvider) User(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockUserProviderMockRecorder) User(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockUserProvider)(nil).User), ctx, email)
}

// MockAppProvider is a mock of AppProvider interface.
type MockAppProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAppProviderMockRecorder
	isgomock struct{}
}

// MockAppProviderMockRecorder is the mock recorder for MockAppProvider.
type MockAppProviderMockRecorder struct {
	mock *MockAppProvider
}

// NewMockAppProvider creates a new mock instance.
func NewMockAppProvider(ctrl *gomock.Controller) *MockAppProvider {
	mock := &MockAppProvider{ctrl: ctrl}
	mock.recorder = &MockAppProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppProvider) EXPECT() *MockAppProviderMockRecorder {
	return m.recorder
}

// App mocks base method.
func (m *MockAppProvider) App(ctx context.Context, appID int32) (entity.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "App", ctx, appID)
	ret0, _ := ret[0].(entity.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// App indicates an expected call of App.
func (mr *MockAppProviderMockRecorder) App(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "App", reflect.TypeOf((*MockAppProvider)(nil).App), ctx, appID)
}

// SaveApp mocks base method.
func (m *MockAppProvider) SaveApp(ctx context.Context, id int32, name, secret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveApp", ctx, id, name, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveApp indicates an expected call of SaveApp.
func (mr *MockAppProviderMockRecorder) SaveApp(ctx, id, name, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveApp", reflect.TypeOf((*MockAppProvider)(nil).SaveApp), ctx, id, name, secret)
}
